---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end
  labels:
    release: "prometheus"
    name: front-end
spec:
  endpoints:
  - path: /metrics
    port: front-end
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: front-end
      app: kube-prometheus-stack-operator
      release: "prometheus"


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: carts
  labels:
    release: "prometheus"
    app: nodeapp
spec:
  endpoints:
  - path: /metrics
    port: carts
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: carts
      app: kube-prometheus-stack-operator
      release: "prometheus"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogue
  labels:
    release: "prometheus"
    name: catalogue
spec:
  endpoints:
  - path: /metrics
    port: catalogue
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: catalogue
      app: kube-prometheus-stack-operator
      release: "prometheus"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders
  labels:
    release: "prometheus"
    name: orders
spec:
  endpoints:
  - path: /metrics
    port: orders
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: orders
      app: kube-prometheus-stack-operator
      release: "prometheus"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment
  labels:
    release: "prometheus"
    name: payment
spec:
  endpoints:
  - path: /metrics
    port: payment
    targetPort: 8080
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: payment
      app: kube-prometheus-stack-operator
      release: "prometheus"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shipping
  labels:
    release: "prometheus"
    name: shipping
spec:
  endpoints:
  - path: /metrics
    port: shipping
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: shipping
      app: kube-prometheus-stack-operator
      release: "prometheus"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user
  labels:
    release: "prometheus"
    name: user
spec:
  endpoints:
  - path: /metrics
    port: user
    targetPort: 80
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: user
      app: kube-prometheus-stack-operator
      release: "prometheus"
