---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end
  namespace: monitoring
  labels:
    release: "monitoring"
    name: front-end
spec:
  endpoints:
  - path: /metrics
    port: front-end
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: front-end
      app: kube-prometheus-stack-operator
      release: "monitoring"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: carts
  namespace: monitoring
  labels:
    release: "monitoring"
    app: nodeapp
spec:
  endpoints:
  - path: /metrics
    port: carts
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: carts
      app: kube-prometheus-stack-operator
      release: "monitoring"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogue
  namespace: monitoring
  labels:
    release: "monitoring"
    name: catalogue
spec:
  endpoints:
  - path: /metrics
    port: catalogue
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: catalogue
      app: kube-prometheus-stack-operator
      release: "monitoring"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders
  namespace: monitoring
  labels:
    release: "monitoring"
    name: orders
spec:
  endpoints:
  - path: /metrics
    port: orders
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: orders
      app: kube-prometheus-stack-operator
      release: "monitoring"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment
  namespace: monitoring
  labels:
    release: "monitoring"
    name: payment
spec:
  endpoints:
  - path: /metrics
    port: payment
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: payment
      app: kube-prometheus-stack-operator
      release: "monitoring"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shipping
  namespace: monitoring
  labels:
    release: "monitoring"
    name: shipping
spec:
  endpoints:
  - path: /metrics
    port: shipping
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: shipping
      app: kube-prometheus-stack-operator
      release: "monitoring"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user
  namespace: monitoring
  labels:
    release: "monitoring"
    name: user
spec:
  endpoints:
  - path: /metrics
    port: user
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: user
      app: kube-prometheus-stack-operator
      release: "monitoring"
