kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      slack_api_url: https://hooks.slack.com/services/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

    route:
      group_by: [alertname, severity, namespace]
      # If an alert isn't caught by a route, send it slack.
      receiver: slack-all
      group_wait: 20s
      group_interval: 4m
      repeatInterval: 30m
      routes:
        - match:
            severity: critical
          receiver: slack-all
    receivers:
    - name: 'slack-all'
      slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        api_url: https://hooks.slack.com/services/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
  configure_secret.sh: |-
    echo 'Configuring Slack hook url.'
    sed -i -e s,API_URL_SECRET,"$SLACK_HOOK_URL",g /etc/alertmanager/config.yml
    exec /bin/alertmanager $*