---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-tenancy
  namespace: argocd
spec: 
  generators: 
    - git: 
        repoURL: https://github.com/Sarahligbe/multi-tenant-deployment.git
        revision: HEAD
        directories: 
          - path: k8s/sock-shop/*
          - path: k8s/portfolio/*
          - path: k8s/monitoring/*
  template: 
    metadata: 
      name: '{{path.basename}}'
    spec: 
      project: multi-tenancy
      source: 
        repoURL: https://github.com/Sarahligbe/multi-tenant-deployment.git
        targetRevision: HEAD
        path: '{{path}}'
      destination: 
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
