---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ordersdb.ordersDbLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.ordersdb.ordersDbLabel }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.ordersdb.ordersDbLabel }}
  template:
    metadata:
      labels:
        name: {{ .Values.ordersdb.ordersDbLabel }}
    spec:
      containers:
      - name: {{ .Values.ordersdb.ordersDbLabel }}
        image: "{{ .Values.ordersdb.image.repo }}:{{ .Values.ordersdb.image.tag }}"
        ports:
        - name: mongo
          containerPort: 27017
        resources:
{{ toYaml .Values.ordersdb.resources | indent 10 }}
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
