---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user.userLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.user.userLabel }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.user.userLabel }}
  template:
    metadata:
      labels:
        name: {{ .Values.user.userLabel }}
    spec:
      containers:
      - name: {{ .Values.user.userLabel }}
        image: "{{ .Values.user.image.repo }}:{{ .Values.user.image.tag }}"
        command:
        - /user
        args:
        - -port={{ .Values.user.containerPort }}
        - -database=mongodb
        - -mongo-host=user-db.{{ .Release.Namespace }}.svc.cluster.local:27017
        resources:
{{ toYaml .Values.user.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.user.containerPort }}
        env:
        - name: MONGO_HOST
          value: user-db:27017
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
{{- if lt (int .Values.user.containerPort) 1024 }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
{{- end }}
          readOnlyRootFilesystem: true
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: {{ .Values.user.containerPort }}
          initialDelaySeconds: 180
          periodSeconds: 3
