---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orders.ordersLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.orders.ordersLabel }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.orders.containerPort }}
  selector:
    name: {{ .Values.orders.ordersLabel }}
