---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.rabbitmqLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.rabbitmq.rabbitmqLabel }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    # the port that this service should serve on
  - port: 5672
    targetPort: 5672
  selector:
    name: {{ .Values.rabbitmq.rabbitmqLabel }}
