---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user.userLabel }}
  labels:
    name: {{ .Values.user.userLabel }}
  annotations:
    prometheus.io/scrape: 'true'
    app: kube-prometheus-stack-operator
    release: "prometheus"
spec:
  ports:
  - port: 80
    name: {{ .Values.user.userLabel }}
    targetPort: {{ .Values.user.containerPort }}
  selector:
    name: {{ .Values.user.userLabel }}
    app: kube-prometheus-stack-operator
    release: "prometheus"
