---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.carts.cartsLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.carts.cartsLabel }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.carts.containerPort }}
  selector:
    name: {{ .Values.carts.cartsLabel }}
