---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartsdb.cartsDbLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.cartsdb.cartsDbLabel }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: {{ .Values.cartsdb.cartsDbLabel }}
