---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.queuemaster.queuemasterLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.queuemaster.queuemasterLabel }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: {{ .Values.queuemaster.queuemasterLabel }}
    targetPort: 80
  selector:
    name: {{ .Values.queuemaster.queuemasterLabel }}
