---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user.userLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.user.userLabel }}
  annotations:
    prometheus.io/scrape = true
    prometheus.io/path: '/actuator/prometheus'
spec:
  ports:
  - port: 80
    name: {{ .Values.user.userLabel }}
    targetPort: {{ .Values.user.containerPort }}
  selector:
    name: {{ .Values.user.userLabel }}
