---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.frontendLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.frontend.frontendLabel }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.frontend.frontendLabel }}
  template:
    metadata:
      labels:
        name: {{ .Values.frontend.frontendLabel }}
    spec:
      containers:
      - name: {{ .Values.frontend.frontendLabel }}
        image: "{{ .Values.frontend.image.repo }}:{{ .Values.frontend.image.tag }}"
        resources:
{{ toYaml .Values.frontend.resources | indent 10 }}
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 30
          periodSeconds: 3
