---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orders.ordersLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.orders.ordersLabel }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.orders.ordersLabel }}
  template:
    metadata:
      labels:
        name: {{ .Values.orders.ordersLabel }}
    spec:
      containers:
      - name: {{ .Values.orders.ordersLabel }}
        image: "{{ .Values.orders.image.repo }}:{{ .Values.orders.image.tag }}"
        env:
         - name: JAVA_OPTS
           value: {{ .Values.java.options }}
        resources:
{{ toYaml .Values.orders.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.orders.containerPort }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
